name: hub
up:
  - railgun
  - node:
      version: v14.15.3
      yarn: 1.22.5
open:
  app: https://hub.myshopify.io

commands:
  __default__: server
  build: yarnpkg run build
  deploy: yarnpkg run deploy
  server:
    aliases: [s]
    run: yarnpkg run start
  test: yarnpkg run test
